### ISSUE TITLE
webpack import

### ISSUE THREAD

**Issue by justoverclockl** [teamtofu/affiliate-plugin-amazon#18]
how can i use this into webpack?

`import affiliate from 'affiliate';` does not work

**Comment by russellsteadman** [comment]
Hi @justoverclockl! See the [plugin documentation](https://affiliate.js.org/plugins/amazon) for a reference. The reference is written in a CommonJS 2 style as opposed to ES Modular Importing, but both should be possible with webpack.

```js
import Affiliate from 'affiliate';
import AffiliatePluginAmazon from 'affiliate-plugin-amazon';
```

Could you provide more details of what you mean by does not work?
